# Generated by Django 6.1.1 on 2026-09-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "homeserver",
                    models.URLField(
                        help_text="The Matrix homeserver URL, e.g. https://matrix.org"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        help_text="The bot's Matrix user ID, e.g. @bot:matrix.org",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("device_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "access_token",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                ("password", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
