# Generated by Django 6.1.1 on 2026-09-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrix_jitsi_bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_id",
                    models.CharField(
                        help_text="The Matrix room ID, e.g. !abc123:matrix.org",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="The language the bot speaks in this room.",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
