# Generated by Django 6.1.1 on 2026-09-08 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrix_jitsi_bot", "0002_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation",
                        to="matrix_jitsi_bot.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        help_text="The Matrix user ID that sent the message.",
                        max_length=255,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        help_text="The Matrix event ID, unique across the homeserver - the canonical way to find this message again.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("body", models.TextField(help_text="The raw message text.")),
                (
                    "server_timestamp",
                    models.DateTimeField(
                        help_text="When the homeserver says the message was sent (distinct from created_at, when we recorded it)."
                    ),
                ),
                (
                    "source",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The raw Matrix event, to retrieve anything not broken out into its own field.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="matrix_jitsi_bot.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CommandReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="The plain-text reply.")),
                (
                    "html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional HTML-formatted reply.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="matrix_jitsi_bot.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        help_text="The Matrix user ID of the member.", max_length=255
                    ),
                ),
                (
                    "membership",
                    models.CharField(
                        default="join",
                        help_text="The member's membership state: join, invite, leave, ban, or knock.",
                        max_length=16,
                    ),
                ),
                (
                    "power_level",
                    models.IntegerField(
                        default=0,
                        help_text="The member's Matrix power level in this room.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="matrix_jitsi_bot.room",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("room", "user_id"), name="unique_room_member"
                    )
                ],
            },
        ),
    ]
