# Generated by Django 6.1.1 on 2026-09-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrix_jitsi_bot", "0003_conversation_message_commandreply_roommember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="event_id",
            field=models.CharField(
                help_text="The Matrix event ID, unique homeserver-wide.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="server_timestamp",
            field=models.DateTimeField(
                help_text="When the homeserver says this was sent."
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="source",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The raw Matrix event, for anything not in its own field.",
            ),
        ),
    ]
