# Generated by Django 6.1.1 on 2026-09-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrix_jitsi_bot", "0010_room_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="last_help_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a full command listing was last sent here - throttles repeating it for every mistyped command in a busy room, see `HelpInteraction.react_to_anything_else`.",
                null=True,
            ),
        ),
    ]
