# Generated by Django 6.1.1 on 2026-09-09 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matrix_jitsi_bot", "0011_room_last_help_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="last_help_at",
        ),
    ]
