# Generated by Django 6.1.1 on 2026-09-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrix_jitsi_bot", "0012_remove_room_last_help_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This room's Matrix display name, as last observed - empty if never observed (e.g. a room from before this field existed, until the bot next sees it).",
                max_length=255,
            ),
        ),
    ]
