# Generated by Django 6.1.1 on 2026-09-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrix_jitsi_bot", "0013_room_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="display_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This account's Matrix profile display name, as last observed - see matrix_jitsi_bot.bot.MatrixJitsiBot._sync_own_display_name and _sync_room_members.",
                max_length=255,
            ),
        ),
    ]
