# Generated by Django 6.1.1 on 2026-09-29 18:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrix_jitsi_bot", "0014_account_display_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pid",
                    models.IntegerField(help_text="The operating system process ID."),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="A random secret this process was started with, telling it apart from any other, also one with the same process ID.",
                        max_length=64,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="JitsiMonitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_state_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the conference last changed.",
                        null=True,
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0,
                        help_text="Reconnect attempts since the connection was lost.",
                    ),
                ),
                (
                    "jitsi_room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitor",
                        to="matrix_jitsi_bot.jitsiroom",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        help_text="The process holding the connection.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitors",
                        to="matrix_jitsi_bot.botprocess",
                    ),
                ),
            ],
        ),
    ]
