# Generated by Django 6.1.1 on 2026-09-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrix_jitsi_bot", "0015_botprocess_jitsimonitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="original_avatar",
            field=models.BinaryField(
                blank=True,
                help_text="The avatar image the room had before the speaker overlay, cached only while `speaker_shown`. Empty: it had none.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="original_avatar_type",
            field=models.CharField(
                blank=True, default="", help_text="Its content type.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="speaker_shown",
            field=models.BooleanField(
                default=False,
                help_text="Whether the room's avatar currently has the speaker overlay. While set, `original_avatar` holds what to restore.",
            ),
        ),
        migrations.AddField(
            model_name="trackedjitsiroom",
            name="show_speaker",
            field=models.BooleanField(
                default=False,
                help_text="Show a speaker on the room's avatar while it's open.",
            ),
        ),
    ]
