# Generated by Django 6.1.1 on 2026-10-01 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "matrix_jitsi_bot",
            "0016_room_original_avatar_room_original_avatar_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "speaker_shown",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the room's avatar currently has the speaker overlay. While set, `original_avatar` holds what to restore.",
                    ),
                ),
                (
                    "original_avatar",
                    models.BinaryField(
                        blank=True,
                        help_text="The avatar image the room had before the speaker overlay, cached only while `speaker_shown`. Empty: it had none.",
                        null=True,
                    ),
                ),
                (
                    "original_avatar_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Its content type.",
                        max_length=255,
                    ),
                ),
                (
                    "room_id",
                    models.CharField(
                        help_text="The space's room ID.", max_length=255, unique=True
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The alias it was asked for, e.g. #space:example.org.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which bot account is in this space.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spaces",
                        to="matrix_jitsi_bot.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="trackedjitsiroom",
            name="avatar_spaces",
            field=models.ManyToManyField(
                blank=True,
                help_text="Spaces whose avatar shows a speaker while it's open.",
                related_name="tracked_by",
                to="matrix_jitsi_bot.space",
            ),
        ),
    ]
