# Generated by Django 6.1.1 on 2026-10-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrix_jitsi_bot", "0017_space_trackedjitsiroom_avatar_spaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="avatar_data_uri",
            field=models.TextField(
                blank=True,
                default="",
                help_text="This account's profile avatar, shrunk, as a data: URI - what is disclosed as its avatar when it joins a Jitsi conference. Empty if it has none: the logo is disclosed then.",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="avatar_mxc",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The Matrix content URI of this account's profile avatar, as last observed - empty if it has none. See `avatar_data_uri`.",
                max_length=255,
            ),
        ),
    ]
