# Generated by Django 6.1.1 on 2026-10-02 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrix_jitsi_bot", "0018_account_avatar_data_uri_account_avatar_mxc"),
    ]

    operations = [
        migrations.AddField(
            model_name="commandreply",
            name="reply_to_event_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The event this is a reply to, if not the message it answers - e.g. a message the bot sent while handling the command.",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="StatusMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        help_text="The Matrix event of the message.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("text", models.TextField(help_text="What the message says now.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_message",
                        to="matrix_jitsi_bot.room",
                    ),
                ),
            ],
        ),
    ]
